### ISSUE TITLE
The question about 3D path planning

### ISSUE THREAD

**Issue by lijoe123** [annafabris/PSO-shortest-path#1]
Hello!
I want to use PSO to do the 3D path planning job, have you do this job before? Could you please give me some advice how to make your 2D job to the 3D.
Thank you so much!

**Comment by annafabris** [comment]
I have not tried to do PSO in 3D before, but the basic principles of PSO can be extended from 2D to 3D.

To do so, you need to make several changes to the code. Here are some that come to my mind:

- Change all the classes in `obstacles.py` from 2D to 3D
- Update the `plot_circle() `and `plot_graph()` functions to plot spheres instead of circles, you may also need to cha.
- Modify the `random_initialization()` function to generate random 3D coordinates and velocities for the particles
- Update the `loss_function()` and `particle_swarm_optimization()` function to use 3D vectors instead of 2D vectors

Lastly, remember that 3D path planning can be more computationally expensive than 2D path planning due to the increased search space complexity. You may need to optimize the PSO algorithm parameters such as the number of particles, the maximum number of iterations, and the inertia weight to ensure efficient convergence.

I hope this advice helps you in your 3D path planning job using PSO!
